Version bump
Fix build-and-publish action

Auto tag

Fix action

diff --git a/.github/workflows/build_publish.yaml b/.github/workflows/build_publish.yaml
--- a/.github/workflows/build_publish.yaml
+++ b/.github/workflows/build_publish.yaml
@@ -1,4 +1,4 @@
-name: Build and Publish
+name: Tag, Build and Publish
 
 on:
   pull_request:
@@ -6,10 +6,40 @@ on:
       - master
     types:
       - closed
+
+permissions:
+  contents: write  # ✅ This grants permission to push tags
+
 jobs:
+  tag:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Extract version
+        id: get_version
+        run: |
+          VERSION_FILE="src/loggerado/__init__.py"
+          if [[ ! -f "$VERSION_FILE" ]]; then
+            echo "Version file not found: $VERSION_FILE"
+            exit 1
+          fi
+          VERSION=$(grep -oP '(?<=__version__ = ")[^"]+' $VERSION_FILE)
+          echo "Extracted version: $VERSION"
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+
+      - name: Tag commit
+        run: |
+          git config --global user.name "github-actions"
+          git config --global user.email "github-actions@github.com"
+          git tag -a "v$VERSION" -m "Release version $VERSION"
+          git push origin "v$VERSION"
+
   build-and-publish:
     name: Build and Publish to PyPI
     runs-on: ubuntu-latest
+    needs: tag
     container:
       image: docker.io/grado/pdm:3.12-alpine
 
@@ -21,4 +51,6 @@ jobs:
         run: pdm build
 
       - name: Publish to PyPI
-        run: pdm publish -u __token__ -P ${{ secrets.PYPI_API_TOKEN }}
+        env:
+          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
+        run: pdm publish -u __token__ -P $PYPI_API_TOKEN
