Fix action

diff --git a/.github/workflows/build_publish.yaml b/.github/workflows/build_publish.yaml
--- a/.github/workflows/build_publish.yaml
+++ b/.github/workflows/build_publish.yaml
@@ -20,9 +20,14 @@ jobs:
       - name: Extract version
         id: get_version
         run: |
-          VERSION=$(grep -oP '__version__\s*=\s*"\K[^"]+' src/loggerado/__init__.py)
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          VERSION_FILE="src/loggerado/__init__.py"
+          if [[ ! -f "$VERSION_FILE" ]]; then
+            echo "Version file not found: $VERSION_FILE"
+            exit 1
+          fi
+          VERSION=$(grep -oP '(?<=__version__ = ")[^"]+' $VERSION_FILE)
           echo "Extracted version: $VERSION"
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
 
       - name: Tag commit
         run: |
